### ISSUE TITLE
Import from Wikipedia

### ISSUE THREAD

**Issue by ghost** [gfwlist/gfwlist_hk#1]
### 香港编年史: 

- hkchronicles.com
- blockedbyhk.com
- goodhope.school

### 2021 香港约章

- 2021hkcharter.com

### 六四记忆，人权博物馆

- 8964museum.com

source: Wikipedia  [香港网络审查](https://zh.wikipedia.org/zh-hans/香港网络审查)

**Comment by cicku** [comment]
hkchronicles.com and 8964museum.com are already added, others are fixed now.
